### ISSUE TITLE
Access to etcd equinix metal project web console

### ISSUE THREAD

**Issue by jmhbnz** [cncf/cluster#242]
### First and Last Name
James Blair

### Email
mail@jamesblair.net

### Company/Organization
Red Hat

### Job Title
Specialist Architect

### Any other relevant details we should know about?
Can someone please grant my equinix account (mail@jamesblair.net) access to  the etcd project equinix web console: https://console.equinix.com/projects/1b8c1eb7-983c-4b40-97e0-e317406e232e 

I am an etcd project reviewer and have been leading work to improve etcd ci on the arm64 self hosted runners, refer https://github.com/etcd-io/etcd/issues/15951

There are five individuals that should have this web console access, they are listed [in this table](https://github.com/etcd-io/etcd/blob/main/Documentation/infra-guide/arm64-infra.md#granting-infrastructure-access ), if possible it would be nice to ensure all five have access as part of this issue (however I'm not certain if all five have equinix accounts etc).

cc @serathius, @ahrtr, @dims, @chaochn47

**Comment by jmhbnz** [comment]
Hey @vielmetti is this something you can help with?  

I can't open a support case in the equinix metal console unless I create a personal organisation which seems unnecessary.

**Comment by idvoretskyi** [comment]
Happy to provide an access once @caniszczyk @jeefy will approve.

**Comment by vielmetti** [comment]
@jmhbnz I wasn't aware of the support case limitation in the console, and that isn't necessarily intentional. If you are getting an error message there I'd like to work out how that is supposed to behave.

We do want you to be able to create support cases though, as appropriate. If you go to the page https://deploy.equinix.com and hit the red "fortress" round logo bottom right there should pop up a support interface with live chat. There is also a page at https://deploy.equinix.com/support/ with support information including an email address if that's the preferred route.

Regarding the personal organization, you would be asked to provide a payment method for any services created on your personal account, but there is no fee with regards to initial account setup.

Much of the console information is also available through our API and CLI.

I'll defer to @idvoretskyi @caniszczyk @jeefy regarding the console access.

**Comment by jmhbnz** [comment]
Ping @caniszczyk , @jeefy for your approval please.

**Comment by idvoretskyi** [comment]
@jmhbnz apologies for the delay. I've noticed you on this file - https://github.com/etcd-io/etcd/blob/main/MAINTAINERS#L20C35-L20C54, so granted you access.

If you want to add other folks as well, we'll need their email addresses so we could invite them.

**Comment by jmhbnz** [comment]
No problem, thanks for the invite, that has worked perfectly for me.

As documented in https://github.com/etcd-io/etcd/blob/main/Documentation/infra-guide/arm64-infra.md#granting-infrastructure-access can you please also send an invite to the following list:

> Name | Github | K8s Slack | Email
> -- | -- | -- | --
> Marek Siarkowicz | @serathius | @ Serathius | marek.siarkowicz@gmail.com
> Benjamin Wang | @ahrtr | @ Benjamin Wang | wachao@vmware.com
> Davanum Srinivas | @dimns | @ Dims | davanum@gmail.com
> Chao Chen | @chaochn47 | @ Chao Chen | chaochn@amazon.com


Those are the other 4 etcd infra admins currently, I believe Dims already has access but Marek, Benjamin and Chao won't.  They may not have Equinix accounts currently but if you send the invite they will be prompted to register or login to existing.

Once invites are sent this issue can be closed, many thanks for your help @idvoretskyi :pray:

**Comment by DimNS** [comment]
Даванум Шринивас | @DimNS | @ Dims | davanum@gmail.com

WTF? It seems to me that someone confused the account on github, I have never participated in these projects and it's not me

**Comment by dims** [comment]
@DimNS it's a typo, please ignore. they are talking about me :)
